# 文章
nav:
  - Jiao:               
    - Navigation:       index.md
    - Profile:          profile.md

  - Infra:
    - Navigation:        src/infra/index.md
    - 🛜 modern network: src/infra/net.md
    - 🛜 router:         src/infra/router.md
    - 🛜 openwrt:        src/infra/openwrt.md
    - 🧮 kvm:            src/infra/kvm.md
    - 💾 oss:            src/infra/oss.md
    - 💾 nfs:            src/infra/nfs.md
    - 💾 smb:            src/infra/smb.md

  - Container:
    - Navigation:        src/container/index.md
    - 🧠 runc:           src/container/runc.md
    - 🐳 docker:         src/container/docker.md
    - 🐳 containerd:     src/container/containerd.md
    - 🚢 kubernetes:     src/container/kubernetes.md

  - Middleware:
    - Navigation:       src/middleware/index.md
    - ⚓️ nginx:         src/middleware/nginx.md
    - 🗄️ postgres:      src/middleware/postgres.md
    - 🗄️ redis:         src/middleware/redis.md
    - 💬 kafka:         src/middleware/kafka.md
  
  - DevOps:
    - Navigation:       src/devops/index.md
    - git:              src/devops/git.md
    - gitlab:           src/devops/gitlab.md
    - cicd:             src/devops/cicd.md
    - prometheus:       src/devops/prometheus.md
    - grafana:          src/devops/grafana.md
  
  - AI:
    - index:             src/ai/index.md
    - d2l:               src/ai/d2l.md

  - Linux:
    - Navigation:        src/linux/index.md
    - 🕒 net:            src/linux/net.md
    - 💾 disk:           src/linux/disk.md
    - 📜 file:           src/linux/file.md
    - 🧮 process:        src/linux/process.md
    - 📝 memory:         src/linux/memory.md
    - 📦 package:        src/linux/package.md
    - 🪟 windows:        src/linux/windows.md

  - C++:
    - cpp:              src/cpp/cpp.md
    - stl:              src/cpp/stl.md
    - thread:           src/cpp/thread.md
    - network:          src/cpp/network.md
    - build-essential:  src/cpp/gcc.md

  - Language:
    - python:           src/language/python.md
    - go:               src/language/go.md

site_name: DAI X.L.
copyright: Copyright © 2020 - Forever. Workers of All Lands
repo_name: dxlcq.github.io
repo_url: https://github.com/dxlcq

theme:
  logo: assets/head.png     # 主图标
  favicon: assets/head.png  # 标签栏图标
  name: material            # 主题
  language: 'zh'            # 中文网站
  palette:                  # 明/暗模式
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to system preference
  features:                 # 功能
    - navigation.top        # 返回顶部的按钮 在上滑时出现
    - navigation.tabs       # 顶部导航
    - content.code.copy     # 代码复制
  font:
    text: 'Noto Serif SC'   # 字体
    code: 'Fira Mono'       # 代码字体

extra:
  generator: false          # 是否显示 Made with Material for MkDocs
  #social:                   # 右下角小标
  #  - icon: fontawesome/solid/paper-plane
  #    link: mailto:<dxlcq@outlook.com>

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-MML-AM_CHTML

markdown_extensions:
  - pymdownx.details        # 详情折叠扩展
  # 代码块
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:     # 代码块高亮
      linenums: true        # 显示行号
      auto_title: true      # 显示编程语言名称
  # latex
  - pymdownx.arithmatex:
      generic: true         # 启用通用的数学公式支持 貌似是 $$ 的支持

plugins:
  - search