# 文章
nav:
  - Jiao:               
    - Navigation:       index.md
    - Profile:          src/jiao/profile.md
    - CV:               src/jiao/cv.md
    - Live:
      - 数字移民:         src/jiao/live/数字移民.md

  - 🪂 Algorithm:
    - Pre:              src/algorithm/pre.md
    - CSP:              src/algorithm/really/csp.md
    - GESP:             src/algorithm/really/gesp.md
    - CIE:              src/algorithm/really/cie.md
    - 基础:
      - 二分:           src/algorithm/base/binary-answer.md
    - 搜索:
      - 深搜:            src/algorithm/search/DFS.md
    - 图论:
      - 二叉树:         src/algorithm/graph/binary-tree.md
    - 动规:
      - 数字三角形:     src/algorithm/dp/number-triangles.md
      - 子序列模型:     src/algorithm/dp/subsequence.md
      #- 背包问题:       src/algorithm/dp/knapsack.md
      #- 状态机:         src/algorithm/dp/state-machine.md
      #- 线性DP:         src/algorithm/dp/linear-dp.md
      #- 状压DP:         src/algorithm/dp/state-compression.md
    #- 数学:
    #- 数论:
    - 数据结构:
      - 链表:           src/algorithm/data-struct/linked-list.md
      - 线段树:         src/algorithm/data-struct/segment-tree.md
    #- 字符串:
    #- 计算几何:
    - raft:             src/algorithm/raft.md

  - 🚀 C/C++:
    - CPP:              src/cpp/cpp.md
    - STL:              src/cpp/stl.md
    - Thread:           src/cpp/thread.md
    - Network:          src/cpp/network.md
    - Qt:               src/cpp/qt.md
    - AV:               src/cpp/av.md
    - ROS:              src/cpp/ros.md
    - 🔩 GCC:           src/cpp/gcc.md
    - 🔩 GDB:           src/cpp/gdb.md
    - 🔩 Make:          src/cpp/make.md
    - 🔩 CMake:         src/cpp/cmake.md
    - 🔩 Perf:          src/cpp/perf.md
    - 📦 GTest:         src/cpp/gtest.md
    - 📦 Boost:         src/cpp/boost.md
    - 📦 OpenSSL:       src/cpp/openssl.md
    - 📦 FFmpeg:        src/cpp/ffmpeg.md
    - 📦 cyclonedds:    src/cpp/cyclonedds.md
    - 📦 subprocess:    src/cpp/subprocess.md
    - 📦 taskflow:      src/cpp/taskflow.md
    - 📦 rocksdb:       src/cpp/rocksdb.md
    - 📦 HMBDC:         src/cpp/hmbdc.md
    - 📦 sqlpp11:       src/cpp/sqlpp11.md
  
  - 🤖 AI:
    - AI:               src/ai/ai.md

  - 🌥️ DevOps:
    - 🧑‍💻 MacOS:         src/dev/macos.md
    - 🐧 Linux:         src/dev/linux.md
    - 📡 OpenWrt:       src/dev/openwrt.md
    - 🪟 Windows:       src/dev/windows.md
        
    #- 💻GitLab:        src/dev/gitlab.md
    - 🚀 Docker:        src/dev/docker.md
    - 🚀 Containerd:    src/dev/containerd.md
    - 🚀 Kubernetes:    src/dev/kubernetes.md
    - 🚀 Prometheus:    src/dev/prometheus.md

    - 🚡 gRPC:          src/dev/grpc.md
    - 🚡 Kafka:         src/dev/kafka.md

    - 📦 PostgreSQL:    src/dev/postgresql.md

    - 💻 Git:           src/dev/git.md
    
    - 💪🏻 Nginx:         src/dev/nginx.md
    - 💪🏻 OpenSSH:       src/dev/openssh.md
    - 💪🏻 Coturn:        src/dev/coturn.md
    - 💪🏻 FRP:           src/dev/frp.md
    - 💪🏻 DDNS:          src/dev/ddns.md
    - 💪🏻 MySQL:         src/dev/mysql.md

  - 🌿 Language:
    - Python:
      - env:            src/language/py/env.md
      - pandas:         src/language/py/pandas.md
      - openpyxl:       src/language/py/openpyxl.md
      - tornado:        src/language/py/tornado.md
      - deeplearning:   src/language/py/deeplearning.md
    - Golang:
      - go:             src/language/go/go.md
      - gin:            src/language/go/gin.md
      - websocket:      src/language/go/websocket.md
    - JS:
      - websocket:      src/language/js/websocket.md
      - webrtc:         src/language/js/webrtc.md
    - Java:
      - main/java:      src/language/java/main_java.md
      - main/resources: src/language/java/main_resources.md
      - test/java:      src/language/java/test_java.md
    - HTML:
      - HTML:           src/language/html/html.md
      - CSS:            src/language/html/css.md
  - 📖 CS:
    - CS:               src/cs/cs.md
    - 操作系统:
      - OS:             src/cs/os/os.md
      - 操作系统结构:    src/cs/os/操作系统结构.md
    - 网络:
      - 冲浪:           src/cs/net/冲浪.md
      - Application:
        - HTTP:         src/cs/net/http.md
      - Transport:
        - TCP:          src/cs/net/tcp.md
        - UDP:          src/cs/net/udp.md
      - Network:
        - IPv4:         src/cs/net/ipv4.md
      - DataLink:
        - Ethernet:     src/cs/net/ethernet.md
        - PPPoE:        src/cs/net/pppoe.md
        - MTU:          src/cs/net/mtu.md
    - 数据结构:
      - 线性表:         src/cs/dataStruct/list.md
      - 队列:           src/cs/dataStruct/queue.md
    - 数据库:
      - 第一章:         src/cs/dataBase/t.md
    - 设计模式:         src/cs/designPattern/designPattern.md
    - 系统架构:         src/cs/systemArchitecture/systemArchitecture.md
    - 工程师:           src/cs/engineer/engineer.md
    - 马克思主义:       src/cs/marx.md
    - 中国近代史:       src/cs/historyOfChina.md
    - 微积分:           src/cs/微积分.md
    - 概率论:           src/cs/概率论.md




site_name: DAI X.L.
copyright: Copyright © 2020 - 2025 Workers of All Lands
repo_name: dxlcq.github.io
repo_url: https://github.com/dxlcq

theme:
  logo: assets/head.png     # 主图标
  favicon: assets/head.png  # 标签栏图标
  name: material            # 主题
  language: 'zh'            # 中文网站
  palette:                  # 明/暗模式
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to system preference
  features:                 # 功能
    - navigation.top        # 返回顶部的按钮 在上滑时出现
    - navigation.tabs       # 顶部导航
    - content.code.copy     # 代码复制
  font:
    text: 'Noto Serif SC'   # 字体
    code: 'Fira Mono'       # 代码字体

extra:
  generator: false          # 是否显示 Made with Material for MkDocs
  #social:                   # 右下角小标
  #  - icon: fontawesome/solid/paper-plane
  #    link: mailto:<dxlcq@outlook.com>

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-MML-AM_CHTML

markdown_extensions:
  - pymdownx.details        # 详情折叠扩展
  # 代码块
  - pymdownx.superfences    # 代码块处理
  - pymdownx.highlight:     # 代码块高亮
      linenums: true        # 显示行号
      auto_title: true      # 显示编程语言名称
  # latex
  - pymdownx.arithmatex:
      generic: true         # 启用通用的数学公式支持 貌似是 $$ 的支持

