version: "3.9"

services:
  web:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime
      - /root/dxlcq.github.io/site:/usr/share/nginx/html
      - /root/dxlcq.github.io/run/default.conf:/etc/nginx/conf.d/default.conf      
      - /etc/letsencrypt/live/dxlcq.cn/fullchain.pem:/etc/letsencrypt/live/dxlcq.cn/fullchain.pem
      - /etc/letsencrypt/live/dxlcq.cn/privkey.pem:/etc/letsencrypt/live/dxlcq.cn/privkey.pem
    restart: unless-stopped